/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uil.Main.WorkSpaceProfiles;

import javax.swing.JPanel;
import model.Business.Business;
import model.Personnel.EmployeeProfile;
import model.DistributorManagement.DistributorPersonProfile;
import model.UserAccountManagement.UserAccount;

/**
 *
 * @author divyansjemni
 */
public class AdminPersonWorkAreaJpanel extends javax.swing.JPanel {
    
    javax.swing.JPanel CardSequencePanel;
    Business business;
    EmployeeProfile emp;
    UserAccount ua;

    /**
     * Creates new form AdminPersonWorkAreaJpanel
     */
    public AdminPersonWorkAreaJpanel(Business b, EmployeeProfile ep, JPanel clp) {
        
        business = b;
        this.CardSequencePanel = clp;
        emp = ep;
        initComponents();
         txtname.setText(emp.getPerson().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnRegulatory = new javax.swing.JButton();
        btnLogisticPartners = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogisticPartners1 = new javax.swing.JButton();
        btnLogisticPartners2 = new javax.swing.JButton();
        btnQueryList = new javax.swing.JButton();
        lblsupermarket = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Work Area");

        btnCustomer.setBackground(new java.awt.Color(0, 204, 255));
        btnCustomer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("VIEW CUSTOMER ACCOUNTS");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnSuppliers.setBackground(new java.awt.Color(0, 204, 255));
        btnSuppliers.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnSuppliers.setText("VIEW SUPPLIERS");
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });

        btnRegulatory.setBackground(new java.awt.Color(0, 204, 255));
        btnRegulatory.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRegulatory.setForeground(new java.awt.Color(255, 255, 255));
        btnRegulatory.setText("VIEW REGULATORY BODIES");
        btnRegulatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegulatoryActionPerformed(evt);
            }
        });

        btnLogisticPartners.setBackground(new java.awt.Color(0, 204, 255));
        btnLogisticPartners.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogisticPartners.setForeground(new java.awt.Color(255, 255, 255));
        btnLogisticPartners.setText("VIEW SUPERMARKETS");
        btnLogisticPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogisticPartnersActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(0, 204, 255));
        btnProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("VIEW PROFILE");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogisticPartners1.setBackground(new java.awt.Color(0, 204, 255));
        btnLogisticPartners1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogisticPartners1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogisticPartners1.setText("VIEW REGULAR USERS");
        btnLogisticPartners1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogisticPartners1ActionPerformed(evt);
            }
        });

        btnLogisticPartners2.setBackground(new java.awt.Color(0, 204, 255));
        btnLogisticPartners2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogisticPartners2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogisticPartners2.setText("VIEW LOGISTICS PARTNER");
        btnLogisticPartners2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogisticPartners2ActionPerformed(evt);
            }
        });

        btnQueryList.setBackground(new java.awt.Color(0, 204, 255));
        btnQueryList.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnQueryList.setForeground(new java.awt.Color(255, 255, 255));
        btnQueryList.setText("QUERY LIST");
        btnQueryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryListActionPerformed(evt);
            }
        });

        lblsupermarket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblsupermarket.setForeground(new java.awt.Color(0, 204, 255));
        lblsupermarket.setText("ADMIN NAME :");

        txtname.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(lblsupermarket)
                        .addGap(44, 44, 44)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegulatory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLogisticPartners1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogisticPartners, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLogisticPartners2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQueryList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsupermarket)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogisticPartners1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogisticPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogisticPartners2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegulatory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQueryList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        
        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        // TODO add your handling code here:
        
         ManageSupplierAccountsJPanel msap = new ManageSupplierAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", msap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnRegulatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegulatoryActionPerformed
        // TODO add your handling code here:
         ManageRegulatorybodyAccountsJPanel msap = new ManageRegulatorybodyAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", msap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnRegulatoryActionPerformed

    private void btnLogisticPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogisticPartnersActionPerformed
        // TODO add your handling code here:
         ManageSupermarketAccountsJPanel msap = new ManageSupermarketAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", msap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnLogisticPartnersActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
 UpdateAdminProfileJPanel admp = new UpdateAdminProfileJPanel(business,emp,ua, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", admp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogisticPartners1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogisticPartners1ActionPerformed
        // TODO add your handling code here:
        
         ManageRegularUserAccountsJPanel admp = new ManageRegularUserAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", admp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnLogisticPartners1ActionPerformed

    private void btnLogisticPartners2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogisticPartners2ActionPerformed
        // TODO add your handling code here:
              ManageLogisticsAccountsJPanel msap = new ManageLogisticsAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageVulns", msap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnLogisticPartners2ActionPerformed

    private void btnQueryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQueryListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnLogisticPartners;
    private javax.swing.JButton btnLogisticPartners1;
    private javax.swing.JButton btnLogisticPartners2;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnQueryList;
    private javax.swing.JButton btnRegulatory;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblsupermarket;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
