package uil.Main.WorkSpaceProfiles;

import javax.swing.JOptionPane;
import model.Business.Business;
import model.SuperMarketManagement.SuperMarketProfile;
import model.DistributorManagement.DistributorPersonProfile;
import ui.Main.WorkSpaceProfiles.OrderManagement.ManageDistributorPersonOrders;
import ui.Main.WorkSpaceProfiles.OrderManagement.ProcessOrder;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccount;
import ui.Main.WorkSpaceProfiles.OrderManagement.ProductPerformanceJPanel;

/**
 *
 * @author divyansjemni
 */
public class DistributorPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    DistributorPersonProfile salesperson;
      UserAccount ua;
      SuperMarketProfile cp;

    public DistributorPersonWorkAreaJPanel(Business b, DistributorPersonProfile spp, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        salesperson = spp;
        initComponents();
         txtname.setText(salesperson.getPerson().getName());
        populateSupermarketDropdown();
           
    }

    private void populateSupermarketDropdown() {
    for (SuperMarketProfile customer : business.getCustomerDirectory().getCustomerlist()) {
        dropUserType.addItem(customer.getPerson().getPersonId());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProductPerformaceReport = new javax.swing.JButton();
        btnProductPerformaceReport1 = new javax.swing.JButton();
        dropUserType = new javax.swing.JComboBox<>();
        lblsupermarket = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 204, 255));

        jButton4.setBackground(new java.awt.Color(0, 204, 255));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BOOK ORDER");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(20, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(240, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 204, 255));
        jButton10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("ORDER HISTORY");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton10.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton10.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("SUPERMARKET");

        btnProductPerformaceReport.setBackground(new java.awt.Color(0, 204, 255));
        btnProductPerformaceReport.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProductPerformaceReport.setForeground(new java.awt.Color(255, 255, 255));
        btnProductPerformaceReport.setText("PRODUCT PERFORMANCE REPORT");
        btnProductPerformaceReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProductPerformaceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductPerformaceReportActionPerformed(evt);
            }
        });

        btnProductPerformaceReport1.setBackground(new java.awt.Color(0, 204, 255));
        btnProductPerformaceReport1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProductPerformaceReport1.setForeground(new java.awt.Color(255, 255, 255));
        btnProductPerformaceReport1.setText("VIEW PROFILE");
        btnProductPerformaceReport1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProductPerformaceReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductPerformaceReport1ActionPerformed(evt);
            }
        });

        dropUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropUserTypeActionPerformed(evt);
            }
        });

        lblsupermarket.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblsupermarket.setForeground(new java.awt.Color(0, 204, 255));
        lblsupermarket.setText("DISTRIBUTOR NAME");

        txtname.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProductPerformaceReport)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnProductPerformaceReport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsupermarket)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProductPerformaceReport, jButton10, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsupermarket)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductPerformaceReport)
                    .addComponent(btnProductPerformaceReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(402, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProductPerformaceReport, jButton10, jButton4});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4IdentifyResourceAssetsActionPerformed
        
// TODO add your handling code here:

    String customerName = dropUserType.getSelectedItem().toString();
    
        // Check if the customer name is empty (though it generally shouldn't be from a dropdown)
        if (customerName == null || customerName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Customer name is required.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        // Find the customer in the directory using the selected name
        SuperMarketProfile selectedCustomer = business.getCustomerDirectory().findCustomer(customerName);

        if (selectedCustomer == null) {
            // If no customer matches the input name, show an error message
            JOptionPane.showMessageDialog(null, "Customer not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method to prevent further execution
        }

        // If customer is found, proceed with the order process
        ProcessOrder aos = new ProcessOrder(business, selectedCustomer, salesperson, CardSequencePanel);

        CardSequencePanel.add("ManageVulns11", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
   


    }//GEN-LAST:event_jButton4IdentifyResourceAssetsActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
 // Pass the 'salesperson' object to 'ManageDistributorPersonOrders'
    ManageDistributorPersonOrders iet = new ManageDistributorPersonOrders(business, CardSequencePanel, salesperson);

    CardSequencePanel.add("FindResourceAsset", iet);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnProductPerformaceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductPerformaceReportActionPerformed
        // TODO add your handling code here:
        
   String customerName = (String) dropUserType.getSelectedItem();

if (customerName == null || customerName.trim().isEmpty()) {
    // Display an error message if no customer is selected
    JOptionPane.showMessageDialog(null, "Please select a customer name.", "Input Required", JOptionPane.ERROR_MESSAGE);
} else {
    // Find the customer in the directory using the selected name
    SuperMarketProfile selectedCustomer = business.getCustomerDirectory().findCustomer(customerName);

    if (selectedCustomer == null) {
        // If no customer matches the input name, show an error message
        JOptionPane.showMessageDialog(null, "Customer not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method to prevent further execution
    }

    // If customer is found, switch to the ProductPerformanceJPanel
    ProductPerformanceJPanel productPerformancePanel = new ProductPerformanceJPanel(business, selectedCustomer, CardSequencePanel);
    CardSequencePanel.add("ProductPerformance", productPerformancePanel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ProductPerformance");
}
    }//GEN-LAST:event_btnProductPerformaceReportActionPerformed

    private void btnProductPerformaceReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductPerformaceReport1ActionPerformed
        // TODO add your handling code here:
        
 UpdateDistributorProfileJPanel admp = new UpdateDistributorProfileJPanel(business, salesperson,ua, CardSequencePanel);
CardSequencePanel.add("ManageVulns", admp);
((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnProductPerformaceReport1ActionPerformed

    private void dropUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropUserTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductPerformaceReport;
    private javax.swing.JButton btnProductPerformaceReport1;
    private javax.swing.JComboBox<String> dropUserType;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblsupermarket;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
