/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uil.Main.WorkSpaceProfiles;


import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.OrderManagement.Order;
import model.OrderManagement.OrderItem;
import model.ProductManagement.Product;
import model.Supplier.SupplierProfile;

/**
 *
 * @author divyansjemni
 */
public class SupplierTop3ProductsPanel extends javax.swing.JPanel {
    
    JPanel CardSequencePanel;
    Business business;
    SupplierProfile sup;
    /**
     * Creates new form SupplierTop3ProductsPanel
     */
    public SupplierTop3ProductsPanel(Business b, SupplierProfile sp, JPanel jp) {
        
        CardSequencePanel = jp;
        business = b;
        sup = sp;
        initComponents();
        displayTop3SellingProducts();
    }
    
    public void displayTop3SellingProducts() {
    DefaultTableModel model = (DefaultTableModel) strPriceRequestsTable.getModel();
    model.setRowCount(0); // Clears the table

    // Get the list of all products from the supplier's catalog
    List<Product> products = sup.getSupplier().getProductCatalog().getProductList();

    // Map to store product and its total sales quantity
    Map<Product, Integer> productSales = new HashMap<>();

    // Iterate over all orders and aggregate sales for products
    for (Order order : business.getMasterOrderList().getOrders()) {
        for (OrderItem oi : order.getOrderItems()) {
            productSales.put(oi.getSelectedProduct(), productSales.getOrDefault(oi.getSelectedProduct(), 0) + oi.getQuantity());
        }
    }

    // Stream the entries of the map, sort them by the total sales quantity in descending order,
    // limit to top 3, and then collect them into a list
    List<Map.Entry<Product, Integer>> topSellingEntries = productSales.entrySet().stream()
            .sorted(Map.Entry.<Product, Integer>comparingByValue().reversed())
            .limit(3)
            .collect(Collectors.toList());

    // Convert list entries to table rows
    for (Map.Entry<Product, Integer> entry : topSellingEntries) {
        Product product = entry.getKey();
        model.addRow(new Object[]{
            product.getName(),
            product.getFloorPrice(),
            product.getCeilingPrice(),
            product.getTargetPrice(),
           (product.getCholesterolPercentage() + product.getSodiumPercentage() + product.getSugarPercentage() + product.getTransfatPercentage()) / 4
        });
    }
}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        strPriceRequestsTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Top 3 Best Selling Products");

        strPriceRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Min Price", "Max Price", "Strategic Price", "Avg of 4 Fat contents"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        strPriceRequestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                strPriceRequestsTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                strPriceRequestsTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(strPriceRequestsTable);

        btnBack.setBackground(new java.awt.Color(0, 204, 255));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void strPriceRequestsTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strPriceRequestsTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_strPriceRequestsTableMouseEntered

    private void strPriceRequestsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strPriceRequestsTableMousePressed

    }//GEN-LAST:event_strPriceRequestsTableMousePressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable strPriceRequestsTable;
    // End of variables declaration//GEN-END:variables
}
