/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Main.WorkSpaceProfiles.OrderManagement;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.ProductManagement.PriceChangeRequest;
import model.ProductManagement.Product;
import model.ProductManagement.ProductReport;
import model.DistributorManagement.DistributorPersonProfile;
import model.Supplier.Supplier;


/**
 *
 * @author Aniruddha
 */
public class STRPriceChangeRequestJPanel extends javax.swing.JPanel {
    
    javax.swing.JPanel CardSequencePanel;
    Business business;
    Product product;
    DistributorPersonProfile salesperson;
    Supplier supplier;
    int newTargetPrice;
    ProductReport productReport;

    /**
     * Creates new form TargetPriceChangeRequestJPanel
     */
    public STRPriceChangeRequestJPanel(JPanel clp, Business business, ProductReport productReport, String selectedSupplier,String productName, int cp, int fp, int tp, String dn ) {
        initComponents();
        
        this.CardSequencePanel = clp;
        this.business = business;
        this.newTargetPrice = newTargetPrice;
        this.productReport = productReport;
        txtDistributor.setText(dn);
        txtSupplierName.setText(selectedSupplier);
        txtName.setText(productName);
        txtFloorPrice.setText(String.valueOf(fp));
        txtCeilingPrice.setText(String.valueOf(cp));
        txtTargetPrice.setText(String.valueOf(tp));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        txtName = new javax.swing.JTextField();
        txtFloorPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTargetPrice = new javax.swing.JTextField();
        txtCeilingPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtSupplierName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDistributor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        txtName.setEnabled(false);

        txtFloorPrice.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("ProductName");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Min Price");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Strategic Price");

        txtCeilingPrice.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Max Price");

        btnSubmit.setBackground(new java.awt.Color(0, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtSupplierName.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Supplier Name");

        btnBack.setBackground(new java.awt.Color(0, 204, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Distributor Name");

        txtDistributor.setEnabled(false);
        txtDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistributorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTargetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtDistributor)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnSubmit)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTargetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSubmit)
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
//        
// String supplierName = txtSupplierName.getText();
//    String productName = txtName.getText();
//    int newTargetPrice;
//    try {
//        newTargetPrice = Integer.parseInt(txtTargetPrice.getText()); // Convert the new target price from text to int
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(null, "Invalid target price format.", "Error", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    // Use the findSupplier method from your SupplierDirectory to get the matched supplier
//    Supplier matchedSupplier = business.getSupplierDirectory().findSupplier(supplierName);
//
//    if (matchedSupplier == null) {
//        JOptionPane.showMessageDialog(null, "Supplier not found.", "Error", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    // Get the product list from the matched supplier
//    ArrayList<Product> products = matchedSupplier.getProductCatalog().getProductList();
//
//    // Loop through the products to find the matching product by name
//    Product matchedProduct = null;
//    for (Product product : products) {
//        if (product.getName().equalsIgnoreCase(productName)) {
//            matchedProduct = product;
//            break;
//        }
//    }
//
//    if (matchedProduct == null) {
//        JOptionPane.showMessageDialog(null, "Product not found.", "Error", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    // If the product is found, update its target price
//    matchedProduct.setTargetPrice(newTargetPrice);
//    JOptionPane.showMessageDialog(null, "Your request for updating the Target Price has been approved and effective immediately", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
//
//    // Optionally, refresh or navigate away after the update
//    if (CardSequencePanel != null) {
//        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
//        layout.previous(CardSequencePanel);
//    }
//
//    // Ensure productReport is initialized before using it
//    if (productReport == null) {
//        productReport = new ProductReport(); // Assuming constructor is defined in ProductReport
//    }
//    productReport.setNewTargetPrice(newTargetPrice);

  String supplierName = txtSupplierName.getText();
  String productName = txtName.getText();
  String distributorName = txtDistributor.getText();
    int newTargetPrice;
    
    // Convert the new target price from text to int and handle any format exception
    try {
        newTargetPrice = Integer.parseInt(txtTargetPrice.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid target price format.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Find the matched supplier
    Supplier matchedSupplier = business.getSupplierDirectory().findSupplier(supplierName);
    if (matchedSupplier == null) {
        JOptionPane.showMessageDialog(null, "Supplier not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create a new price change request
    PriceChangeRequest request = new PriceChangeRequest();
    request.setProductName(productName);
    request.setNewTargetPrice(newTargetPrice);
    request.setSupplierName(supplierName);
    request.setSalesPersonName(distributorName);
    request.setIsApproved(false);

    // Add the new request to the supplier's list of price change requests
    matchedSupplier.addPriceChangeRequest(request);

    // Inform the salesperson that the request was submitted
    JOptionPane.showMessageDialog(null, "Price change request submitted.", "Submission Successful", JOptionPane.INFORMATION_MESSAGE);

    // Optionally, navigate away from the current panel
    if (CardSequencePanel != null) {
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }
    
    }//GEN-LAST:event_btnSubmitActionPerformed

    public int getNewTargetPrice() {
        return newTargetPrice;
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel); 

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistributorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtCeilingPrice;
    private javax.swing.JTextField txtDistributor;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtTargetPrice;
    // End of variables declaration//GEN-END:variables
}
